### ISSUE TITLE
adds -js-display: flex; before flexbox prefixes

### ISSUE THREAD

**Issue by m-e-h** [7rulnik/postcss-flexibility#3]
Not sure if anyone else is getting this. I opened an issue with autoprefixer too https://github.com/postcss/autoprefixer/issues/608

**Comment by 7rulnik** [comment]
@m-e-h now if you will use it after Autoprefixer you will get this: 

Source:
```css
a {
    display: -webkit-flex;
    display: -ms-flexbox;
    -js-display: flex;
    display: flex
}
```

Old bug:
```css
a {
    -js-display: flex;
    display: -webkit-flex;
    -js-display: flex;
    display: -ms-flexbox;
    -js-display: flex;
    display: flex
}
```

Fixed:
```css
a {
    display: -webkit-flex;
    display: -ms-flexbox;
    -js-display: flex;
    display: flex
}
```
